---
url: http://localhost:4000
baseurl: ''
title: DNS Investment club
description: Helping you strike gold with your domain strategy.
avatar: "/assets/img/d.png"
language: en
icons:
  rss: true
  email: 
  github: 
  bitbucket: 
  twitter: dnsinvestment
  facebook: 
  google_plus: 
  tumblr: 
  behance: 
  dribbble: 
  flickr: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  wordpress: 
  youtube: UCi4-j_JFdRAQyELOKvbkf4A
permalink: pretty
google_analytics: 
disqus: 
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts
recent_posts_num: 10
paginate: 10
paginate_path: page/:num
share_buttons:
  twitter: true
  facebook: false
  hatena: false
ogp:
  image_url: http://qckanemoto.github.io/jekyll-qck-theme/assets/img/ogp.png
  fb:
    admin: 
    app_id: 
gems:
- jemoji
include:
- _pages
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - strikethrough
  - superscript
  - with_toc_data
  - tables
  - footnotes
  - no_intra_emphasis
highlighter: pygments
excerpt_separator: "<!--more-->"
sass:
  sass_dir: _sass
  style: :compressed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- vendor
color1: 7E5686
color2: A5AAD9
color3: E8F9A2
color4: F8A13F
color5: BA3C3D
theme_num: 95
